# --- Windows 98 Terminal Skin ---
font_family      Fixedsys Excelsior
font_size        12.0
disable_ligatures always

# Pure Retro Console Colors
foreground       #ffffff
background       #000000
cursor           #ffffff

# Retro Window Padding
window_padding_width 4
